if &t_Co > 2 || has("gui_running")
  if has("syntax")
    syntax on
  endif
  set hlsearch
  if &term == "kon" || &term == "linux" || &term == "jfbterm"
    set bg=dark
  endif
endif
filetype plugin indent on
autocmd FileType text setlocal textwidth=80
set ruler
set showcmd
set autoindent
set tabstop=4
set expandtab
set shiftwidth=4
set incsearch
set fileformat=unix
