FROM php:7-fpm
# COPY vimrc /root/.vimrc
# RUN echo "alias ls='ls -hp'" >> /root/.bashrc \
# && echo "alias ll='ls -l'" >> /root/.bashrc \
# && echo "alias la='ls -la'" >> /root/.bashrc
# Install necessary packages
# RUN apt-get update \
# &&  apt-get install -y vim
# RUN mkdir /var/log/php-fpm && chown www-data:www-data /var/log/php-fpm
# COPY docker.conf /usr/local/etc/php-fpm.d/docker.conf
